server:  
  port: ${PORT:8686}

spring:  
  application:
    name: gateway-server

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
    
zuul:
  ignoredServices: '*'
  routes:  
    micro:
      path: /**
      sensitiveHeaders:
      serviceId: micro1
    auth:
      path: /**
      sensitiveHeaders:
      serviceId: auth-server
      
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/