server:  
  port: ${PORT:8686}

spring:  
  application:
    name: gateway-server

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
    
zuul:
  ignoreSecurityHeaders: false
  ignoredServices: '*'
  routes:
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId: auth-server
    category:
      path: /category/**
      sensitiveHeaders:
      serviceId: category-service
      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/