server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server   
  security:
   user:
    name: root
    password: password
security:
  oauth2:
    client:
      client-id: acme
      client-secret: secret
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/