server:  
  port: ${PORT:9999}
spring:  
  application:
    name: auth-server
  postgresql:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/hoptq
      username: hoptq
      password: 12345678
      driver-class-name: org.postgresql.Driver
      connection-test-query: SELECT 1
  mysql:
    datasource:
      jdbc-url: jdbc:mysql://server2/db_2
      username: user
      password: password
      driver-class-name: com.mysql.jdbc.Driver
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : update
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/